databases:
  - name: micronaut
    databaseName: micronaut_rynn
    user: micronaut_rynn_user



services:
  - type: web
    name: spend-smartly
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut_rynn
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false